# Generated by Django 5.1.7 on 2025-03-21 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('electronica', 'Electrónica'), ('celulares', 'Celulares y Accesorios'), ('computacion', 'Computación'), ('consolas_videojuegos', 'Consolas y Videojuegos'), ('televisores', 'Televisores y Audio'), ('electrodomesticos', 'Electrodomésticos'), ('hogar_muebles', 'Hogar y Muebles'), ('decoracion', 'Decoración para el Hogar'), ('cocina', 'Cocina y Menaje'), ('herramientas', 'Herramientas y Construcción'), ('otros', 'Otros')], default='Electronica', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp'])])),
            ],
        ),
    ]
