# Generated by Django 5.1.7 on 2025-03-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_product_user_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
