# Generated by Django 5.1.7 on 2025-03-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_customer_email_remove_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('efectivo', 'Efectivo'), ('paypal', 'PayPal'), ('cripto', 'Criptomoneda')], default='tarjeta', max_length=10)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
            ],
        ),
    ]
