# Generated by Django 5.1.7 on 2025-03-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_customer_email_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=10),
            preserve_default=False,
        ),
    ]
