# Generated by Django 5.1.7 on 2025-03-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.TextField(default='not provided', max_length=10),
            preserve_default=False,
        ),
    ]
